import os
import openai

class AIPipelines:
    def __init__(self, api_key=None):
        if api_key:
            openai.api_key = api_key
        else:
            # Try env var or leave empty for now
            pass
            
    def generate_idf_from_text(self, nlp_text, config):
        """
        Placeholder for Layer 4 Logic.
        In the future, this will call OpenAI to modify a template IDF.
        For now, it returns a dummy valid IDF content.
        """
        print(f"[AI] Generating IDF for: {nlp_text}")
        
        # MOCK IDF CONTENT (Minimal valid object to prove flow)
        mock_idf = f"""
  ! IDF Generated by SmartHVAC AI
  ! Description: {nlp_text}
  ! Config: {config}

  Version, 22.1.0;

  Building,
    Simple One Zone,          !- Name
    0.0,                      !- North Axis {{deg}}
    Suburbs,                  !- Terrain
    0.04,                     !- Loads Convergence Tolerance Value
    0.004,                    !- Temperature Convergence Tolerance Value {{deltaC}}
    FullInteriorAndExterior,  !- Solar Distribution
    25,                       !- Maximum Number of Warmup Days
    6;                        !- Minimum Number of Warmup Days
        """
        return mock_idf
